// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iucpulkisaslruevopvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1Y3B1bGtpc2FzbHJ1ZXZvcHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzI5MjgsImV4cCI6MjA2NDkwODkyOH0.scgRntH-z3pVwRe9KnGmIe1iNLTWXRbMRzC2qTeWxd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);